import Calculate from '@sections/Calculate'
import Choose from '@sections/Choose'
import Cryptocurrencies from '@sections/Cryptocurrencies'
import Cta from '@sections/Cta'
import Features from '@sections/Features'
import Footer from '@sections/Footer'
import Header from '@sections/Header'
import Hero from '@sections/Hero'
import Valuation from '@sections/Valuation'
import Head from 'next/head'

export default function Home() {
	return (
		<>
			<Head>
				<title>Crappo</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/logo.png' />
			</Head>
			<Header />
			<main>
				<Hero />
				<Valuation />
				<Choose />
				<Calculate />
				<Cryptocurrencies />
				<Features />
				<Cta />
				<Footer />
			</main>
		</>
	)
}

// https://tweenpages.vercel.app/docs
